### ISSUE TITLE
大哥PHP没用框架啊，厉害啊，原生挺厉害的

### ISSUE THREAD

**Issue by iszmxw** [sx6316/xsgl#2]

**Comment by iszmxw** [comment]
先关注支持一下

**Comment by sx6316** [comment]
用个毛框架啊，就写个接口用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午4:57
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送： &nbsp;“ Subscribed” <subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)





 
先关注支持一下
  
— 
您收到此消息是因为您已订阅该线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by sx6316** [comment]
主要还是我太水了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午4:57
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)

**Comment by sx6316** [comment]
说起也无奈，只能等以后技术提升了再回来弄了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午4:57
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)





 
先关注支持一下

**Comment by iszmxw** [comment]
还可以啊，你之前是写前端的吗？

**Comment by sx6316** [comment]
不是，我之前什么都不写，想往前端发展，发现前端也不行，打算去培训了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午5:25
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送:&nbsp;"随行"<1874737488@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)





 
还可以啊，你之前是写前端的吗？

**Comment by iszmxw** [comment]
去哪里培训？

**Comment by sx6316** [comment]
去哪不行，就是钱的问题，不过都是去要就去大的培训机构，国内也就那几家大的it培训了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午5:28
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送:&nbsp;"随行"<1874737488@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)





 
去哪里培训？

**Comment by iszmxw** [comment]
好吧，你还没上班吗，还是上班了，要去系统精进一下

**Comment by sx6316** [comment]
应届毕业，主要还是太难找工作了，我就要个2500一个月都没人要，可能今年疫情问题吧，很不景气




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午5:31
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送:&nbsp;"随行"<1874737488@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)





 
好吧，你还没上班吗，还是上班了，要去系统精进一下

**Comment by iszmxw** [comment]
好吧，那确实比较难，我今年还准备换工作的，现在只能暂时先稳住

**Comment by sx6316** [comment]
1874737488&nbsp; 加我qq，交个朋友，感觉这样聊天太怪异了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Yep"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午5:37
收件人:&nbsp;"sx6316/xsgl"<xsgl@noreply.github.com&gt;;
抄送:&nbsp;"随行"<1874737488@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sx6316/xsgl] 大哥PHP没用框架啊，厉害啊，原生挺厉害的 (#2)





 
好吧，那确实比较难，我今年还准备换工作的，现在只能暂时先稳住

**Comment by iszmxw** [comment]
哈哈
